nimrodkor/checkov

checkov/kubernetes/checks/ApiServerAuditLogMaxSize.py
tests/kubernetes/checks/example_ApiServerAuditLogMaxSize/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerAuditLogMaxSize/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAuditLogMaxSize/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAuditLogMaxSize.py

Ensure that the --audit-log-maxsize argument is set to 100 or as appropriate
Id = CKV_K8S_94

CKV_K8S_94  api server audit log max size

---

checkov/kubernetes/checks/ApiServerAuditLogMaxBackup.py
tests/kubernetes/checks/example_ApiServerAuditLogMaxBackup/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerAuditLogMaxBackup/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAuditLogMaxBackup/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAuditLogMaxBackup.py

Ensure that the --audit-log-maxbackup argument is set to 10 or as appropriate
Id = CKV_K8S_93

CKV_K8S_93 api server audit log max backup

---

checkov/terraform/checks/resource/aws/KubernetesSecretsEncryptedUsingCMK.py
tests/terraform/checks/resource/aws/test_KubernetesSecretsEncryptedUsingCMK.py

CKV_AWS_106
Ensure Kubernetes Secrets are encrypted using Customer Master Keys (CMKs) managed in AWS KMS 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#provider

Implement CKV_AWS_106

---

checkov/kubernetes/checks/ApiServerAuthorizationModeNotAlwaysAllow.py
tests/kubernetes/checks/example_ApiServerAuthorizationModeNotAlwaysAllow/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeNotAlwaysAllow/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeNotAlwaysAllow/ApiServer-PASSED-2.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeNotAlwaysAllow/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAuthorizationModeNotAlwaysAllow.py

Ensure that the --authorization-mode argument is not set to AlwaysAllow
Id = CKV_K8S_74

CKV_K8S_74 api server authorization mode not always allow

---

checkov/terraform/checks/resource/gcp/GKEMetadataServerisEnabled.py
checkov/terraform/checks/resource/gcp/GKEReleaseChannel.py
tests/terraform/checks/resource/gcp/test_GKEMetadataServerisEnabled.py
tests/terraform/checks/resource/gcp/test_GKEMetadataServerisEnabled/main.tf
tests/terraform/checks/resource/gcp/test_GKEReleaseChannel.py
tests/terraform/checks/resource/gcp/test_GKEReleaseChannel/main.tf

1. Ensure the GKE Metadata Server is Enabled
in google_container_cluster or google_container_node_pool
node_config{
workload_metadata_config {
node_metadata="GKE_METADATA_SERVER"
}
}
2. When creating New Clusters - Automate GKE version management using Release Channels
property Release Channels in clusters
release_channel {
channel=var.release_channel
}

metadata and release channel checks

---

checkov/terraform/checks/resource/aws/ELBUsesSSL.py
tests/terraform/checks/resource/aws/test_ELBUsesSSL.py
tests/terraform/runner/test_plan_runner.py

Ensure that Elastic Load Balancer(s) uses SSL certificates provided by AWS Certificate Manager.

Add CKV_AWS_127 - Ensure that Elastic Load Balancer(s) uses SSL

---

checkov/kubernetes/checks/ApiServerKubeletHttps.py
tests/kubernetes/checks/example_ApiServerKubeletHttps/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerKubeletHttps/ApiServer-PASSED-2.yaml
tests/kubernetes/checks/example_ApiServerKubeletHttps/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerKubeletHttps.py

Ensure that the --kubelet-https argument is set to true
Id = CKV_K8S_71

CKV_K8S_71 k8s api server kubelet https

---

checkov/graph/terraform/runner.py
checkov/terraform/runner.py
tests/terraform/runner/test_runner.py

1. Allow creating definitions context and passing the context & tf_definitions to the tf_runner for scans on persistant graph
2. Fix overriding the local_graph class

Expose option to re-use graph when running the scan

---

checkov/graph/terraform/checks/aws/SGToEC2AndENI.yaml
tests/graph/terraform/checks/resources/SGToEC2AndENI/expected.yaml
tests/graph/terraform/checks/resources/SGToEC2AndENI/main.tf

CKV2_AWS_5 - Ensure that Security Groups are attached to EC2 instances or elastic network interfaces (ENIs)

CKV2_AWS_5

---

checkov/kubernetes/checks/ApiServerEtcdCertAndKey.py
tests/kubernetes/checks/example_ApiServerEtcdCertAndKey/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerEtcdCertAndKey/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerEtcdCertAndKey/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerEtcdCertAndKey.py

Ensure that the --etcd-certfile and --etcd-keyfile arguments are set as appropriate
Id = CKV_K8S_99

CKV_K8S_99 k8s api server etcd key and cert

---

checkov/kubernetes/checks/ApiServerKubeletClientCertAndKey.py
tests/kubernetes/checks/example_ApiServerKubeletClientCertAndKey/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerKubeletClientCertAndKey/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerKubeletClientCertAndKey/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerKubeletClientCertAndKey.py

Ensure that the --kubelet-client-certificate and --kubelet-client-key arguments are set as appropriate
Id = CKV_K8S_72

CKV_K8S_72 k8s api server kubelet client cert/key

---

checkov/terraform/checks/resource/aws/DynamodbPointInTimeRecoveryEnabled.py
checkov/terraform/checks/resource/aws/ElasticsearchInVPC.py
tests/terraform/checks/resource/aws/test_ElasticsearchInVPC.py

Implement CKV_AWS_137 and modify the category in CKV_AWS_125 (after consult to Gilad)
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticsearch_domain
Ensure that Elasticsearch is configured inside a VPC

CKV_AWS_137

---

checkov/common/util/type_forcers.py
checkov/terraform/checks/resource/gcp/GKELegacyInstanceMetadataDisabled.py
tests/terraform/checks/resource/gcp/test_GKELegacyInstanceMetadataDisabled.py
tests/terraform/checks/resource/gcp/test_GKELegacyInstanceMetadataDisabled/main.tf

11. Ensure legacy Compute Engine instance metadata APIs are Disabled 
"From GKE 1.12 onwards, disable-legacy-endpoints is set to true by the API"
check GKE version
By checking that min_master_version  is set to 1.12 or higher?

CKV_GCP_67 Ensure legacy Compute Engine instance metadata APIs are Disabled 

---

checkov/terraform/checks/resource/aws/S3KMSEncryptedByDefault.py
tests/terraform/checks/resource/aws/test_S3KMSEncryptedByDefault.py

Ensure that S3 buckets are encrypted with KMS by default
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#apply_server_side_encryption_by_default

CKV_AWS_145

---

checkov/terraform/checks/resource/gcp/GKESecureBootforShieldedNodes.py
tests/terraform/checks/resource/gcp/test_GKEReleaseChannel/main.tf
tests/terraform/checks/resource/gcp/test_GKESecureBootforShieldedNodes.py
tests/terraform/checks/resource/gcp/test_GKESecureBootforShieldedNodes/main.tf
tests/terraform/checks/resource/gcp/test_GoogleCloudSqlDatabasePublicallyAccessible/main.tf

Ensure Secure Boot for Shielded GKE Nodes is Enabled
check exists and set as defaults to false
shielded_instance_config {
enable_secure_boot =true
}

Check/CKV_GCP_73 Ensure Secure Boot for Shielded GKE Nodes is Enabled

---

checkov/terraform/checks/resource/aws/RedshiftClusterAllowVersionUpgrade.py
tests/terraform/checks/resource/aws/test_RedshiftClusterAllowVersionUpgrade.py

Add check CKV_AWS_147 - Ensured that redshift cluster allowing version upgrade by default

Add check CKV_AWS_147 

---

checkov/terraform/checks/resource/gcp/GKEKubernetesRBACGoogleGroups.py
tests/terraform/checks/resource/gcp/test_GKEKubernetesRBACGoogleGroups.py
tests/terraform/checks/resource/gcp/test_GKEKubernetesRBACGoogleGroups/main.tf

https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control
CKV_GCP_65
The authenticator_groups_config block supports:
security_group 
check that this field has any value.

CKV_GCP_65:Manage Kubernetes RBAC users with Google Groups for GKE

---

checkov/terraform/checks/resource/gcp/GKEPrivateNodes.py
tests/terraform/checks/resource/gcp/test_GKEPrivateNodes.py
tests/terraform/checks/resource/gcp/test_GKEPrivateNodes/main.tf

Ensure clusters are created with Private Nodes
https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters
Looks for private_cluster_config in google_container_cluster

CKV_GCP_64 Check/Ensure clusters are created with Private Nodes

---

checkov/terraform/checks/resource/azure/FunctionAppHttpVersionLatest.py
tests/terraform/checks/resource/azure/test_FunctionAppHttpVersionLatest.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#http2_enabled
Ensure that 'HTTP Version' is the latest if used to run the function app

CKV_AZURE_67

---

checkov/terraform/checks/resource/azure/AzureDataExplorerDoubleEncryptionEnabled.py
tests/terraform/checks/resource/azure/test_AzureDataExplorerDoubleEncryptionEnabled.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_cluster#double_encryption_enabled
Ensure that Azure Data Explorer uses double encryption

CKV_AZURE_75

---

checkov/terraform/checks/resource/azure/AzureServiceFabricClusterUseADAuth.py
tests/terraform/checks/resource/azure/test_AzureServiceFabricClusterUseADAuth.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_fabric_cluster#azure_active_directory
Ensures that Active Directory is used for authentication for Service Fabric

CKV_AZURE_125

---

checkov/terraform/checks/resource/azure/MySQLEncryptionEnaled.py
checkov/terraform/checks/resource/azure/PostgersSQLEncryptionEnaled.py
tests/terraform/checks/resource/azure/test_MySQLEncryptionEnaled.py
tests/terraform/checks/resource/azure/test_PostgersSQLEncryptionEnaled.py

CKV_AZURE_96 - Ensure that PostgreSQL server enables infrastructure encryption
CKV_AZURE_130 - Ensure that MySQL server enables infrastructure encryption

CKV_AZURE_96/CKV_AZURE_130

---

checkov/terraform/checks/resource/azure/PostgressSQLGeoBackupEnabled.py
tests/terraform/checks/resource/azure/test_PostgresSQLGeoBackupEnabled.py

CKV_AZURE_102 - Ensure that PostgreSQL server enables geo-redundant backups

CKV_AZURE_102

---

checkov/graph/terraform/graph_builder/local_graph.py
checkov/graph/terraform/utils/utils.py
checkov/graph/terraform/variable_rendering/evaluate_terraform.py
checkov/graph/terraform/variable_rendering/renderer.py
checkov/terraform/context_parsers/parsers/locals_context_parser.py
tests/graph/terraform/graph_builder/test_local_graph.py
tests/graph/terraform/resources/variable_rendering/render_dictionary_tfvars/main.tf
tests/graph/terraform/resources/variable_rendering/render_dictionary_tfvars/terraform.tfvars
tests/graph/terraform/resources/variable_rendering/terraform-aws-eks-master/eks.tf
tests/graph/terraform/resources/variable_rendering/terraform-aws-eks-master/variables.tf
tests/graph/terraform/utils/test_utils.py
tests/graph/terraform/variable_rendering/expected_data.py
tests/graph/terraform/variable_rendering/test_renderer.py

1. Moved the local_graph method `_attribute_has_nested_attributes` to utils package
2. Fixed a bug when trying to replace a value in a string with a non-string value (in `evaluate_terraform`)
3. When evaluating non-rendered value, evaluate only inner-most values and do it recursively on lists/sets/dictionaries to avoid evaluating non-string values into strings.
4. Fixed `list index out of range` by checking the length in locals_context_parser
5. Fixed `expected string or bytes-like object` by correctly rendering values from variables with maps as default values

Variable evaluation bug fixes

---

checkov/terraform/checks_infra/solvers/connections_solvers/base_connection_solver.py
checkov/terraform/checks_infra/solvers/connections_solvers/connection_exists_solver.py
tests/graph/terraform/checks_infra/connection_solvers/and_connection_solver/ALBConnectedToHTTPS.yaml
tests/graph/terraform/checks_infra/connection_solvers/and_connection_solver/test_solver.py
tests/graph/terraform/resources/lb/main.tf

This PR solves the following issue:
Assume we have a policy that checks if:
- connection exists between resource `A` to resource `B`
- `B` has attribute `x`
- Return all `A` that comply to this policy
In the input file we have resources `A1`, `B1` and `B2`
we have edges `A1->B1` and `A1->B2`
`B1` has attribute `x` but `B2` doesn't.
According to the policy definitions, `A1` should fail, before this fix `A1` would pass due to the connection to `B1`.

Solve policies with resources that have multiple connections
