checkov/terraform/checks/resource/azure/AppServiceFTPSState.py
checkov/terraform/checks/resource/azure/SecurityCenterContactEmails.py
tests/terraform/checks/resource/azure/test_AppServiceFTPSState.py
tests/terraform/checks/resource/azure/test_SecurityCenterContactEmails.py
tests/terraform/runner/test_runner.py

Added CKV2_AZURE_12 and CKV2_AZURE_39

CKV2_AZURE_12 & CKV2_AZURE_39

---

checkov/terraform/checks/resource/aws/RedshitClusterPubliclyAvailable.py
checkov/terraform/checks/resource/aws/SageMakerInternetAccessDisabled.py
checkov/terraform/checks/resource/aws/VPCEndpointAcceptanceConfigured.py
tests/terraform/checks/resource/aws/test_RedshiftClusterPubliclyAccessible.py
tests/terraform/checks/resource/aws/test_SageMakerInternetAccessDisabled.py
tests/terraform/checks/resource/aws/test_VPCEndpointAcceptanceConfigured.py

added checks CKV_AWS_123, CKV_AWS_122, CKV_AWS_87

---

checkov/kubernetes/checks/ApiServerBasicAuthFile.py
tests/kubernetes/checks/example_ApiServerBasicAuthFile/ApiServerBasicAuthFile-FAILED.yaml
tests/kubernetes/checks/example_ApiServerBasicAuthFile/ApiServerBasicAuthFile-PASSED.yaml
tests/kubernetes/checks/test_ApiServerBasicAuthFile.py

Added a new check of K8s API Server basic auth file (CKV_K8S_69)

---

checkov/kubernetes/checks/ApiServerServiceAccountLookup.py
tests/kubernetes/checks/example_ApiServerServiceAccountLookup/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerServiceAccountLookup/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerServiceAccountLookup/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerServiceAccountLookup.py

Ensure that the --service-account-lookup argument is set to true  
Id = CKV_K8S_96

CKV_K8S_96 api server service account lookup

---

checkov/kubernetes/checks/ApiServerAuditLog.py
tests/kubernetes/checks/example_ApiServerAuditLog/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAuditLog/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAuditLog.py

Ensure that the --audit-log-path argument is set
Check - CKV_K8S_91

CKV_K8S_91 Feat(Check):  Ensure api server audit log is set

---

checkov/terraform/checks/resource/aws/ElasticCacheAutomaticBackup.py
checkov/terraform/checks/resource/base_resource_negative_value_check.py
tests/terraform/checks/resource/aws/test_ElasticCacheAutomaticBackup.py

CKV_AWS_112

---

checkov/graph/terraform/graph_builder/local_graph.py
checkov/graph/terraform/graph_manager.py
checkov/graph/terraform/runner.py

1. Refactor `_build_edges` to be standalone, so it will be easy to override.
2. Pass into `build_graph_from_source_directory` the class that will inherit `LocalGraph`

Refactor edges building to allow inheritance

---

checkov/terraform/checks/resource/gcp/GKEEnableShieldedNodes.py
tests/terraform/checks/resource/gcp/test_GKEEnableShieldedNodes.py
tests/terraform/checks/resource/gcp/test_GKEEnableShieldedNodes/main.tf

3. Ensure Shielded GKE Nodes are Enabled
this is true when:
```
enable_shielded_nodes=true
```
Defaults to False, so only valid if set and true.

CKV_GCP_71 Check/enabledshieldednodes

---

checkov/kubernetes/checks/ApiServerAuthorizationModeNode.py
tests/kubernetes/checks/example_ApiServerAuthorizationModeNode/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeNode/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeNode/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAuthorizationModeNode.py

Ensure that the --authorization-mode argument includes Node
Id = CKV_K8S_75

CKV_K8S_75 api server auth mode Node

---

checkov/terraform/checks/resource/aws/DynamodbPointInTimeRecoveryEnabled.py
tests/terraform/checks/resource/aws/test_DynamodbPointInTimeRecoveryEnabled.py

Ensure that that point in time recovery is enabled for Amazon DynamoDB tables
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table#point_in_time_recovery

CKV_AWS_125

---

checkov/graph/terraform/checks/aws/APIGWLoggingLevelsDefinedProperly.yaml
checkov/graph/terraform/checks/aws/GuardDutyIsEnabled.yaml
checkov/graph/terraform/checks/aws/VAconfiguredToSendReports.yaml
checkov/graph/terraform/checks/aws/VAconfiguredToSendReportsToAdmins.yaml
checkov/graph/terraform/checks/aws/VAisEnabledInStorageAccount.yaml
checkov/graph/terraform/checks/aws/VAsetPeriodicScansOnSQL.yaml
checkov/graph/terraform/checks/aws/VPChasRestrictedSG.yaml
tests/graph/terraform/checks/resources/APIGWLoggingLevelsDefinedProperly/expected.yaml
tests/graph/terraform/checks/resources/APIGWLoggingLevelsDefinedProperly/main.tf
tests/graph/terraform/checks/resources/GuardDutyIsEnabled/expected.yaml
tests/graph/terraform/checks/resources/GuardDutyIsEnabled/main.tf
tests/graph/terraform/checks/resources/VAconfiguredToSendReports/expected.yaml
tests/graph/terraform/checks/resources/VAconfiguredToSendReports/main.tf
tests/graph/terraform/checks/resources/VAconfiguredToSendReportsToAdmins/expected.yaml
tests/graph/terraform/checks/resources/VAconfiguredToSendReportsToAdmins/main.tf
tests/graph/terraform/checks/resources/VAisEnabledInStorageAccount/expected.yaml
tests/graph/terraform/checks/resources/VAisEnabledInStorageAccount/main.tf
tests/graph/terraform/checks/resources/VAsetPeriodicScansOnSQL/expected.yaml
tests/graph/terraform/checks/resources/VAsetPeriodicScansOnSQL/main.tf
tests/graph/terraform/checks/resources/VPChasRestrictedSG/expected.yaml
tests/graph/terraform/checks/resources/VPChasRestrictedSG/main.tf

- CKV2_AZURE_2
- CKV2_AZURE_3
- CKV2_AZURE_4
- CKV2_AZURE_5
- CKV2_AWS_3
- CKV2_AWS_4
- CKV2_AWS_12
--> passed tests in bc-graphs repo

Batch of yaml checks

---

checkov/graph/terraform/runner.py
tests/graph/terraform/resources/graph_files_test/more_vars.tf
tests/graph/terraform/resources/graph_files_test/pass_s3.tf
tests/graph/terraform/resources/graph_files_test/variables.tf
tests/graph/terraform/runner/test_runner.py

Handle file scanning in terraform graph runner

---

checkov/terraform/checks/resource/aws/DBInstanceMonitoring.py
tests/terraform/checks/resource/aws/test_DBInstanceMonitoring.py

added new check + UT

---

checkov/terraform/checks/resource/aws/RDSEnableIAMAuthentication.py
tests/terraform/checks/resource/aws/test_RDSEnableIAMAuthentication.py

Ensure that an Amazon RDS Clusters and Instances have AWS Identity and Access Management (IAM) authentication enabled

Add CKV_AWS_128

---

checkov/graph/terraform/checks/aws/StorageContainerActivityLogsNotPublic.yaml
tests/graph/terraform/checks/resources/StorageContainerActivityLogsNotPublic/expected.yaml
tests/graph/terraform/checks/resources/StorageContainerActivityLogsNotPublic/main.tf

CKV2_AZURE_8 - Ensure the storage container storing the activity logs is not publicly accessible

CKV2_AZURE_8

---

checkov/graph/terraform/checks/aws/StorageCriticalDataEncryptedCMK.yaml
tests/graph/terraform/checks/resources/StorageCriticalDataEncryptedCMK/expected.yaml
tests/graph/terraform/checks/resources/StorageCriticalDataEncryptedCMK/main.tf

CKV2_AZURE_1 - Ensure storage for critical data are encrypted with Customer Managed Key

CKV2_AZURE_1

---

checkov/kubernetes/checks/ApiServerTlsCertAndKey.py
tests/kubernetes/checks/example_ApiServerTlsCertAndKey/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerTlsCertAndKey/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerTlsCertAndKey/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerTlsCertAndKey.py

Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate
Id = CKV_K8S_100

CKV_K8S_100 k8s api server tls cert and key

---

checkov/kubernetes/checks/ApiServerAuthorizationModeRBAC.py
tests/kubernetes/checks/example_ApiServerAuthorizationModeRBAC/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeRBAC/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeRBAC/ApiServer-PASSED-2.yaml
tests/kubernetes/checks/example_ApiServerAuthorizationModeRBAC/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAuthorizationModeRBAC.py

Ensure that the --authorization-mode argument includes RBAC
Id = CKV_K8S_77

CKV_K8S_77 k8s api server RBAC auth

---

checkov/graph/checks/checks_infra/registry.py
checkov/graph/terraform/checks_infra/registry.py
checkov/graph/terraform/graph_builder/utils.py
checkov/graph/terraform/runner.py
checkov/graph/terraform/utils/utils.py
tests/graph/terraform/checks/test_yaml_policies.py

Also, add generate_possible_strings_from_wildcards utils method

Support external policies and persistant data injection

---

checkov/terraform/checks/resource/aws/RDSDeletionProtection.py
tests/terraform/checks/resource/aws/test_RDSDeletionProtection.py

added RDSDeletionProtection

---

checkov/kubernetes/checks/EtcdCertAndKey.py
tests/kubernetes/checks/example_EtcdCertAndKey/Etcd-FAILED-2.yaml
tests/kubernetes/checks/example_EtcdCertAndKey/Etcd-FAILED.yaml
tests/kubernetes/checks/example_EtcdCertAndKey/Etcd-PASSED.yaml
tests/kubernetes/checks/test_EtcdCertAndKey.py

Ensure that the --cert-file and --key-file arguments are set as appropriate
Id = CKV_K8S_116 

CKV_K8S_116 k8s etcd certificate and key files

---

checkov/terraform/checks/resource/aws/ELBCrossZoneEnable.py
tests/terraform/checks/resource/aws/test_ELBCrossZoneEnable.py

Ensure that ELB is cross-zone-load-balancing enabled

CKV_AWS_138

---

checkov/terraform/checks/resource/aws/RedshiftClusterKMSKey.py
tests/terraform/checks/resource/aws/test_RedshiftClusterKMSKey.py

added aws_redshift_cluster check

---

checkov/terraform/checks/resource/aws/CloudformationStackNotificationArns.py
tests/terraform/checks/resource/aws/test_CloudformationStackNotificationArns.py

added CloudformationStackNotificationArns

---

checkov/terraform/checks/resource/aws/S3BucketObjectLock.py
tests/terraform/checks/resource/aws/test_S3BucketObjectLock.py

added S3BucketObjectLock check

---

checkov/terraform/checks/resource/aws/DynamoDBTablesEncrypted.py
tests/terraform/checks/resource/aws/test_DynamoDBTablesEncrypted.py

CKV_AWS_111

---

checkov/graph/terraform/runner.py

Expose graph manager for tf graph runner for inheritance

---

checkov/terraform/checks/resource/aws/SubnetPublicIP.py
tests/terraform/checks/resource/aws/test_SubnetPublicIP.py

add_check_CKV_AWS_103

---

checkov/terraform/checks/resource/gcp/GKEEnableVPCFlowLogs.py
tests/terraform/checks/resource/gcp/test_GKEEnableVPCFlowLogs.py
tests/terraform/checks/resource/gcp/test_GKEEnableVPCFlowLogs/main.tf

6.Enable VPC Flow Logs and Intranode Visibility
GKEEnableVPCFlowLogs
CKV_GCP_74
https://cloud.google.com/kubernetes-engine/docs/how-to/intranode-visibility

CKV_GCP_74 Enable intranode visibility

---

checkov/terraform/checks/resource/aws/EC2EBSOptimized.py
tests/terraform/checks/resource/aws/test_CKV_AWS_135.py
tests/terraform/checks/resource/aws/test_EC2EBSOptimized.py

added check + UT for CKV_AWS_135

---

checkov/terraform/checks/resource/aws/DBInstanceBackupRetentionPeriod.py
tests/terraform/checks/resource/aws/test_DBInstanceBackupRetentionPeriod.py

added new check CKV_AWS_133 + UT

---

checkov/terraform/checks/resource/aws/RDSClusterSnapshotEncrypted.py
tests/terraform/checks/resource/aws/test_RDSClusterSnapshotEncrypted.py

CKV_AWS_153

---

checkov/terraform/checks/resource/aws/RDSClusterEncrypted.py
tests/terraform/checks/resource/aws/test_RDSClusterEncrypted.py

added new check CKV_AWS_149 + UT

---

checkov/terraform/checks/resource/aws/CodeBuildEncrypted.py
tests/terraform/checks/resource/aws/test_CodeBuildEncrypted.py

added new check CKV_AWS_150 + UT

---

checkov/terraform/checks/resource/aws/ECRRepositoryEncrypted.py
tests/terraform/checks/resource/aws/test_ECRRepositoryEncrypted.py

Ckv aws 154

---

checkov/graph/terraform/parser.py
checkov/graph/terraform/runner.py

Allow module and block inheritance

---

checkov/terraform/checks/resource/aws/S3BucketReplicationConfiguration.py
tests/graph/terraform/runner/test_runner.py
tests/terraform/checks/resource/aws/test_S3BucketReplicationConfiguration.py
tests/terraform/runner/test_runner.py

added S3BucketReplicationConfiguration check

---

checkov/terraform/checks/resource/azure/RedisCachePublicNetworkAccessEnabled.py
tests/terraform/checks/resource/azure/test_RedisCachePublicNetworkAccessEnabled.py

added RedisCachePublicNetworkAccessEnabled check

---

checkov/terraform/checks/resource/azure/AppServiceUsedAzureFiles.py
tests/terraform/checks/resource/azure/test_AppServiceUsedAzureFiles.py

Add check CKV_AZURE_88 - Ensure that app services use Azure Files

CKV_AZURE_88 - Ensure that app services use Azure Files

---

checkov/kubernetes/checks/SchedulerBindAddress.py
tests/kubernetes/checks/example_SchedulerBindAddress/SchedulerBindAddress-FAILED-2.yaml
tests/kubernetes/checks/example_SchedulerBindAddress/SchedulerBindAddress-FAILED.yaml
tests/kubernetes/checks/example_SchedulerBindAddress/SchedulerBindAddress-PASSED.yaml
tests/kubernetes/checks/test_SchedulerBindAddressy.py

CKV_K8S_115

---

checkov/kubernetes/checks/KubeControllerManagerTerminatedPods.py
tests/kubernetes/checks/example_KubeControllerManagerTerminatedPods/ApiServer-FAILED-2.yaml
tests/kubernetes/checks/example_KubeControllerManagerTerminatedPods/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_KubeControllerManagerTerminatedPods/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_KubeControllerManagerTerminatedPods.py

added CKV_K8S_106 check + UT

---

checkov/kubernetes/checks/KubletEventCapture.py
tests/kubernetes/checks/example_KubletEventCapture/KubletEventCapture-FAILED.yaml
tests/kubernetes/checks/example_KubletEventCapture/KubletEventCapture-PASSED.yaml
tests/kubernetes/checks/test_KubletEventCapture.py

CKV_K8S_147

---

checkov/kubernetes/checks/KubeletCryptographicCiphers.py
tests/kubernetes/checks/example_KubeletCryptographicCiphers/KubeletCryptographicCiphers-FAILED.yaml
tests/kubernetes/checks/example_KubeletCryptographicCiphers/KubeletCryptographicCiphers-PASSED.yaml
tests/kubernetes/checks/test_KubeletCryptographicCiphers.py

CKV_K8S_151

---

checkov/kubernetes/checks/SchedulerProfiling.py
tests/kubernetes/checks/example_SchedulerProfiling/SchedulerProfiling-FAILED.yaml
tests/kubernetes/checks/example_SchedulerProfiling/SchedulerProfiling-PASSED.yaml
tests/kubernetes/checks/test_SchedulerProfiling.py

CKV_K8S_114

---

checkov/kubernetes/checks/KubletRotateKubeletServerCertificate.py
tests/kubernetes/checks/example_KubletRotateKubeletServerCertificate/KubletRotateKubeletServerCertificate-FAILED.yaml
tests/kubernetes/checks/example_KubletRotateKubeletServerCertificate/KubletRotateKubeletServerCertificate-PASSED.yaml
tests/kubernetes/checks/test_KubletRotateKubeletServerCertificate.py

CKV_K8S_150

---

checkov/kubernetes/checks/KubletRotateCertificates.py
tests/kubernetes/checks/example_KubletRotateCertificates/KubletRotateCertificates-FAILED.yaml
tests/kubernetes/checks/example_KubletRotateCertificates/KubletRotateCertificates-PASSED.yaml
tests/kubernetes/checks/test_KubletRotateCertificates.py

CKV_K8S_149

---

checkov/kubernetes/checks/PeerClientCertAuthTrue.py
tests/kubernetes/checks/example_PeerClientCertAuthTrue/PeerClientCertAuthTrue-FAILED.yaml
tests/kubernetes/checks/example_PeerClientCertAuthTrue/PeerClientCertAuthTrue-FAILED2.yaml
tests/kubernetes/checks/example_PeerClientCertAuthTrue/PeerClientCertAuthTrue-PASSED.yaml
tests/kubernetes/checks/test_PeerClientCertAuthTrue.py

Ckv k8s 121

---

checkov/terraform/checks/resource/gcp/GKEBinaryAuthorization.py
tests/terraform/checks/resource/gcp/test_GKEBinaryAuthorization.py
tests/terraform/checks/resource/gcp/test_GKEBinaryAuthorization/main.tf

10.Ensure use of Binary Authorization
CKV_GCP_66
check for enable_binary_authorization =true

CKV_GCP_66 BinaryAuthorization

---

checkov/terraform/checks/resource/azure/NSGRuleUDPAccessRestricted.py
tests/terraform/checks/resource/azure/test_NSGRuleUDPAccessRestricted.py

Ensure that UDP Services are restricted from the Internet

CKV_AZURE_77

---

checkov/terraform/checks/resource/azure/AppServiceEnableFailedRequest.py
tests/terraform/checks/resource/azure/test_AppServiceEnableFailedRequest.py

Add check CKV_AZURE_66 - Ensure that App service enables failed request tracing

CKV_AZURE_66

---

checkov/terraform/checks/resource/azure/AppServiceHttpLoggingEnabled.py
tests/terraform/checks/resource/azure/test_AppServiceHttpLoggingEnabled.py

Ensure that App service enables HTTP logging
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service

CKV_AZURE_63

---

checkov/terraform/checks/resource/azure/AppServiceDetailedErrorMessagesEnabled.py
tests/terraform/checks/resource/azure/test_AppServiceDetailedErrorMessagesEnabled.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service
Ensure that App service enables detailed error messages

CKV_AZURE_65

---

checkov/terraform/checks/resource/azure/RemoteDebggingNotEnabled.py
tests/terraform/checks/resource/azure/test_RemoteDebuggingNotEnabled.py

CKV_AZURE_72

---

checkov/terraform/checks/resource/azure/AppServiceIdentityProviderEnabled.py
tests/terraform/checks/resource/azure/test_AppServiceIdentityProviderEnabled.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#type
Ensure that Managed identity provider is enabled for app services

CKV_AZURE_71

---

checkov/terraform/checks/resource/azure/AzureBatchAccountUsesKeyVaultEncryption.py
tests/terraform/checks/resource/azure/test_AzureBatchAccountUsesKeyVaultEncryption.py

Ensure that Azure Batch account uses key vault to encrypt data
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_account#key_vault_reference

CKV_AZURE_76

---

checkov/kubernetes/checks/KubeControllerManagerBlockProfiles.py
tests/kubernetes/checks/example_KubeControllerManagerBlockProfiles/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_KubeControllerManagerBlockProfiles/ApiServer-FAILED_2.yaml
tests/kubernetes/checks/example_KubeControllerManagerBlockProfiles/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_KubeControllerManagerBlockProfiles.py

https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
Ensure that the --profiling argument is set to false

CKV_K8S_107

---

checkov/kubernetes/checks/KubeControllerManagerServiceAccountCredentials.py
tests/kubernetes/checks/example_KubeControllerManagerServiceAccountCredentials/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_KubeControllerManagerServiceAccountCredentials/ApiServer-PASSED.yaml
tests/kubernetes/checks/example_KubeControllerManagerServiceAccountCredentials/ApiServer-UNKNOWN.yaml
tests/kubernetes/checks/test_KubeControllerManagerServiceAccountCredentials.py

Ensure that the --use-service-account-credentials argument is set to true

CKV_K8S_108

---

checkov/terraform/checks/resource/azure/DataExplorerUsesDiskEncryption.py
tests/terraform/checks/resource/azure/test_DataExplorerUsesDiskEncryption.py

CKV_AZURE_74

---

checkov/kubernetes/checks/KubeControllerManagerServiceAccountPrivateKeyFile.py
tests/kubernetes/checks/example_KubeControllerManagerServiceAccountPrivateKeyFile/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_KubeControllerManagerServiceAccountPrivateKeyFile/ApiServer-PASSED-2.yaml
tests/kubernetes/checks/example_KubeControllerManagerServiceAccountPrivateKeyFile/ApiServer-PASSED.yaml
tests/kubernetes/checks/test_KubeControllerManagerServiceAccountPrivateKeyFile.py

Ensure that the --service-account-private-key-file argument is set as appropriate

CKV_K8S_110

---

checkov/terraform/checks/resource/azure/AzureManagedDiskEncryptionSet.py
tests/terraform/checks/resource/azure/test_AzureManagedDiskEncryptionSet.py

Add check CKV_AZURE_93 - Ensure that managed disks use a specific set…

CKV_AZURE_93

---

checkov/terraform/checks/resource/azure/AzureContainerGroupDeployedIntoVirtualNetwork.py
tests/terraform/checks/resource/azure/test_AzureContainerGroupDeployedIntoVirtualNetwork.py

CKV_AZURE_98 - Ensure that Azure Container Container group is deployed into virtual network

CKV_AZURE_98 

---

checkov/terraform/checks/resource/azure/AzureContainerGroupDeployedIntoVirtualNetwork.py
checkov/terraform/checks/resource/azure/CosmosDBHaveCMK.py
tests/terraform/checks/resource/azure/test_AzureContainerGroupDeployedIntoVirtualNetwork.py
tests/terraform/checks/resource/azure/test_CosmosDBHaveCMK.py

Add check CKV_AZURE_100 - Ensure that Cosmos DB accounts have customer-managed keys to encrypt data at rest

CKV_AZURE_100

---

checkov/terraform/checks/resource/azure/CosmosDBDisablesPublicNetwork.py
tests/terraform/checks/resource/azure/test_CosmosDBDisablesPublicNetwork.py

Add check CKV_AZURE_101 - Ensure that Azure Cosmos DB disables public network access
you can see default values here:
https://github.com/terraform-providers/terraform-provider-azurerm/pull/9236/files

CKV_AZURE_101 

---

checkov/terraform/checks/resource/azure/EventgridDomainNetworkAccess.py
tests/terraform/checks/resource/azure/test_EventgridDomainNetworkAccess.py

added new check + UT (CKV_AZURE_106)

---

checkov/terraform/checks/resource/azure/FunctionAppsAccessibleOverHttps.py
tests/terraform/checks/resource/azure/test_FunctionAppsAccessibleOverHttps.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#https_only
Ensure that Function apps is only accessible over HTTPS

CKV_AZURE_70

---

checkov/kubernetes/checks/ApiServerAdmissionControlAlwaysAdmit.py
tests/kubernetes/checks/example_ApiServerAdmissionControlAlwaysAdmit/ApiServerAdmissionControlAlwaysAdmit-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAdmissionControlAlwaysAdmit/ApiServerAdmissionControlAlwaysAdmit-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAdmissionControlAlwaysAdmit.py

CKV_K8S_79 - Ensure that the admission control plugin AlwaysAdmit is not set

---

checkov/kubernetes/checks/ApiServerAdmissionControlEventRateLimit.py
tests/kubernetes/checks/example_ApiServerAdmissionControlEventRateLimit/ApiServerAdmissionControlEventRateLimit-FAILED.yaml
tests/kubernetes/checks/example_ApiServerAdmissionControlEventRateLimit/ApiServerAdmissionControlEventRateLimit-PASSED.yaml
tests/kubernetes/checks/test_ApiServerAdmissionControlEventRateLimit.py

CKV_K8S_78 - Ensure that the admission control plugin EventRateLimit is set

---

checkov/graph/checks/checks_infra/base_parser.py
checkov/graph/checks/checks_infra/registry.py
checkov/graph/terraform/checks_infra/nx_checks_parser.py
checkov/graph/terraform/runner.py

Fix external checks loading and external registry loading

---

checkov/terraform/checks/resource/azure/AutomationEncrypted.py
tests/terraform/checks/resource/azure/test_AutomationEncrypted.py

added AutomationEncrypted check and test

---

checkov/terraform/checks/resource/azure/VMStorageOsDisk.py
tests/terraform/checks/resource/azure/test_VMStorageOsDisk.py

added VMStorageOsDisk check and test

---

checkov/terraform/checks/resource/azure/AppServiceDisallowCORS.py
tests/terraform/checks/resource/azure/test_AppServiceDisallowedCORS.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#cors
Ensure that CORS disallows every resource to access function apps

CKV_AZURE_57

---

checkov/terraform/checks/resource/azure/FunctionAppDisallowCORS.py
tests/terraform/checks/resource/azure/test_FunctionAppDisallowCORS.py

CKV_AZURE_62
Ensure that CORS disallows every resource to access function appshttps://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#allowed_origins

CKV_AZURE_62

---

checkov/terraform/checks/resource/azure/RedisCacheEnableNonSSLPort.py
tests/terraform/checks/resource/azure/test_RedisCacheEnableNonSSLPort.py

RedisCacheEnableNonSSLPort check and test

---

checkov/kubernetes/checks/ControllerManagerBindAddress.py
tests/kubernetes/checks/example_ControllerManagerBindAddress/ControllerManagerBindAddress-FAILED-2.yaml
tests/kubernetes/checks/example_ControllerManagerBindAddress/ControllerManagerBindAddress-FAILED.yaml
tests/kubernetes/checks/example_ControllerManagerBindAddress/ControllerManagerBindAddress-PASSED.yaml
tests/kubernetes/checks/test_ControllerManagerBindAddress.py

CKV_K8S_113

---

checkov/terraform/checks/resource/azure/DataFactoryUsesGitRepository.py
tests/terraform/checks/resource/azure/test_DataFactoryUsesGitRepository.py

CKV_AZURE_103

---

checkov/terraform/checks/resource/azure/KeyVaultAllowsFirewallRulesSettings.py
tests/terraform/checks/resource/azure/test_KeyVaultAllowsFirewallRulesSettings.py

CKV_AZURE_109

---

checkov/terraform/checks/resource/azure/KeyVaultEnablesPurgeProtection.py
tests/terraform/checks/resource/azure/test_KeyVaultEnablesPurgeProtection.py

CKV_AZURE_110

---

checkov/terraform/checks/resource/azure/KeyVaultEnablesSoftDelete.py
tests/terraform/checks/resource/azure/test_KeyVaultEnablesSoftDelete.py

CKV_AZURE_111

---

checkov/terraform/checks/resource/azure/AKSEnablesPrivateClusters.py
tests/terraform/checks/resource/azure/test_AKSEnablesPrivateClusters.py

CKV_AZURE_115

---

checkov/terraform/checks/resource/azure/AKSUsesAzurePoliciesAddon.py
tests/terraform/checks/resource/azure/test_AKSUsesAzurePoliciesAddon.py

CKV_AZURE_116

---

checkov/terraform/checks/resource/azure/ApplicationGatewayEnablesWAF.py
tests/terraform/checks/resource/azure/test_ApplicationGatewayEnablesWAF.py

CKV_AZURE_120

---

checkov/terraform/checks/resource/azure/VMScaleSetsAutoOSImagePatchingEnabled.py
tests/terraform/checks/resource/azure/test_VMScaleSetsAutoOSImagePatchingEnabled.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set#automatic_os_upgrade
Ensure that automatic OS image patching is enabled for Virtual Machine Scale Sets

CKV_AZURE_95

---

checkov/terraform/checks/resource/azure/SecretContentType.py
tests/terraform/checks/resource/azure/test_SecretContentType.py

Ensure that key vault secrets have "content_type" set
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret#content_type

CKV_AZURE_114

---

checkov/terraform/checks/resource/azure/AKSUsesDiskEncryptionSet.py
tests/terraform/checks/resource/azure/test_AKSUsesDiskEncryptionSet.py

Ckv azure 117

---

checkov/terraform/checks/resource/azure/MySQLServerPublicAccessDisabled.py
checkov/terraform/checks/resource/azure/PostgreSQLServerPublicAccessDisabled.py
checkov/terraform/checks/resource/azure/SQLServerPublicAccessDisabled.py
tests/terraform/checks/resource/azure/test_MySQLServerPublicAccessDisabled.py
tests/terraform/checks/resource/azure/test_PostgreSQLServerPublicAccessDisabled.py
tests/terraform/checks/resource/azure/test_SQLServerPublicAccessDisabled.py

CKV_AZURE_131/132/133

---

checkov/terraform/checks/resource/azure/NetworkInterfaceEnableIPForwarding.py
tests/terraform/checks/resource/azure/test_NetworkInterfaceEnableIPForwarding.py

added NetworkInterfaceEnableIPForwarding check and test

---

checkov/terraform/checks/resource/azure/AzureFrontDoorEnablesWAF.py
tests/terraform/checks/resource/azure/test_AzureFrontDoorEnablesWAF.py

CKV_AZURE_121

---

checkov/graph/terraform/runner.py
checkov/terraform/runner.py

Use definitions context consistently

---

checkov/terraform/checks/resource/azure/ActiveDirectoryUsedAuthenticationServiceFabric.py
tests/terraform/checks/resource/azure/test_ActiveDirectoryUsedAuthenticationServiceFabric.py

CKV_AZURE_126

---

checkov/terraform/checks/resource/azure/AzureSearchPublicNetworkAccessDisabled.py
tests/terraform/checks/resource/azure/test_AzureSearchPublicNetworkAccessDisabled.py

Ensure that Azure Cognitive Search disables public network access
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/search_service#public_network_access_enabled

CKV_AZURE_124

---

checkov/terraform/checks/resource/azure/SynapseWorkspaceEnablesManagedVirtualNetworks.py
tests/terraform/checks/resource/azure/test_SynapseWorkspaceEnablesManagedVirtualNetworks.py

CKV_AZURE_137

---

checkov/terraform/checks/resource/azure/StorageSyncPublicAccessDisabled.py
tests/terraform/checks/resource/azure/test_StorageSyncPublicAccessDisabled.py

CKV_AZURE_134

---

checkov/terraform/checks/resource/azure/MySQLGeoBackupEnabled.py
tests/terraform/checks/resource/azure/test_MySQLGeoBackupEnabled.py

CKV_AZURE_94 - Ensure that My SQL server enables geo-redundant backups

CKV_AZURE_94

---

checkov/kubernetes/checks/KubeControllerManagerRootCAFile.py
tests/kubernetes/checks/example_KubeControllerManagerRootCAFile/ApiServer-FAILED.yaml
tests/kubernetes/checks/example_KubeControllerManagerRootCAFile/ApiServer-PASSED.yaml
tests/kubernetes/checks/example_KubeControllerManagerRootCAFile/ApiServer-PASSED_2.yaml
tests/kubernetes/checks/test_KubeControllerManagerRootCAFile.py

Ensure that the --root-ca-file argument is set as appropriate

CKV_K8S_111

---

checkov/kubernetes/checks/KubeControllerManagerRotateKubeletServerCertificate.py
tests/kubernetes/checks/example_KubeControllerManagerRotateKubeletServerCertificate/KubeControllerManagerRotateKubeletServerCertificate-FAILED.yaml
tests/kubernetes/checks/example_KubeControllerManagerRotateKubeletServerCertificate/KubeControllerManagerRotateKubeletServerCertificate-PASSED.yaml
tests/kubernetes/checks/test_KubeControllerManagerRotateKubeletServerCertificate.py

Ensure that the RotateKubeletServerCertificate argument is set to true

CKV_K8S_112

---

checkov/terraform/checks/resource/azure/DataLakeStoreEncryption.py
tests/terraform/checks/resource/azure/test_DataLakeStoreEncryption.py

added new check + UT (CKV_AZURE_105)

---

checkov/terraform/checks/resource/azure/VMEncryptionAtHostEnabled.py
tests/terraform/checks/resource/azure/test_VMEncryptionAtHostEnabled.py

CKV_AZURE_97

---

checkov/kubernetes/checks/ApiServerEncryptionProviders.py
checkov/kubernetes/checks/ApiServerStrongCryptographicCiphers.py
tests/kubernetes/checks/example_ApiServerEncryptionProviders/ApiServerEncryptionProviders-FAILED.yaml
tests/kubernetes/checks/example_ApiServerEncryptionProviders/ApiServerEncryptionProviders-PASSED.yaml
tests/kubernetes/checks/example_ApiServerStrongCryptographicCiphers/ApiServerStrongCryptographicCiphers-FAILED.yaml
tests/kubernetes/checks/example_ApiServerStrongCryptographicCiphers/ApiServerStrongCryptographicCiphers-PASSED.yaml
tests/kubernetes/checks/test_ApiServerEncryptionProviders.py
tests/kubernetes/checks/test_ApiServerStrongCryptographicCiphers.py

Ckv k8 s 10x

---

checkov/terraform/checks/resource/azure/KeyBackedByHSM.py
tests/terraform/checks/resource/azure/test_KeyBackedByHSM.py

Ensure that key vault key is backed by HSM
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key#key_type

CKV_AZURE_112

---

checkov/terraform/checks/resource/azure/StorageAccountEnablesSecureTransfer.py
tests/terraform/checks/resource/azure/test_StorageAccountEnablesSecureTransfer.py

implementation of CKV_AZURE_135

---

checkov/kubernetes/checks/EtcdPeerFiles.py
tests/kubernetes/checks/example_EtcdPeerFiles/EtcdPeerFiles-FAILED.yaml
tests/kubernetes/checks/example_EtcdPeerFiles/EtcdPeerFiles-PASSED.yaml
tests/kubernetes/checks/test_EtcdPeerFiles.py

CKV_K8S_119

---

checkov/kubernetes/checks/EtcdClientCertAuth.py
tests/kubernetes/checks/example_EtcdClientCertAuth/Etcd-FAILED-2.yaml
tests/kubernetes/checks/example_EtcdClientCertAuth/Etcd-FAILED.yaml
tests/kubernetes/checks/example_EtcdClientCertAuth/Etcd-PASSED.yaml
tests/kubernetes/checks/test_EtcdClientCertAuth.py

Ensure that the --client-cert-auth argument is set to true
Id = CKV_K8S_117

CKV_K8S_117 k8s etcd client certificate auth

---

checkov/kubernetes/checks/EtcdAutoTls.py
tests/kubernetes/checks/example_EtcdAutoTls/Etcd-FAILED.yaml
tests/kubernetes/checks/example_EtcdAutoTls/Etcd-PASSED-2.yaml
tests/kubernetes/checks/example_EtcdAutoTls/Etcd-PASSED.yaml
tests/kubernetes/checks/test_EtcdAutoTls.py

Ensure that the --auto-tls argument is not set to true
Id = CKV_K8S_118

CKV_K8S_118 k8s etcd auto tls

---

checkov/kubernetes/checks/ApiServerkubeletCertificateAuthority.py
tests/kubernetes/checks/example_ApiServerkubeletCertificateAuthority/ApiServerkubeletCertificateAuthority-FAILED.yaml
tests/kubernetes/checks/example_ApiServerkubeletCertificateAuthority/ApiServerkubeletCertificateAuthority-PASSED.yaml
tests/kubernetes/checks/test_ApiServerkubeletCertificateAuthority.py

CKV_K8S_73

---

checkov/terraform/checks/resource/azure/AppGWUseWAFMode.py
checkov/terraform/checks/resource/azure/WAFSpecifiedModeAppGW.py
tests/terraform/checks/resource/azure/test_WAFSpecifiedModeAppGW.py

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy#policy_settings
Ensure that Application Gateway uses WAF in "Detection" or "Prevention" modes

CKV_AZURE_122

---

checkov/terraform/checks/resource/azure/FrontdoorUseWAFMode.py
tests/terraform/checks/resource/azure/test_FrontdoorUseWAFMode.py

CKV_AZURE_123

---

checkov/graph/terraform/parser.py

Fix sorting different types of list items

---

checkov/terraform/checks/resource/azure/MySQLTreatDetectionEnabled.py
checkov/terraform/checks/resource/azure/PostgresSQLTreatDetectionEnabled.py
tests/terraform/checks/resource/azure/test_MySQLTreatDetectionEnabled.py
tests/terraform/checks/resource/azure/test_PostgresSQLTreatDetectionEnabled.py

CKV_AZURE_127 - Ensure that My SQL server enables Threat detection policy
CKV_AZURE_128 - Ensure that Postgres SQL server enables Threat detection policy

CKV_AZURE_127/CKV_AZURE_128

---

checkov/graph/terraform/checks/azure/AzureMSSQLServerHasSecurityAlertPolicy.yaml
checkov/graph/terraform/checks/azure/AzureStorageAccountsUseCustomerManagedKeyForEncryption.yaml
checkov/graph/terraform/checks/azure/AzureSynapseWorkspacesHaveNoIPFirewallRulesAttached.yaml
checkov/graph/terraform/checks_infra/nx_checks_parser.py
tests/graph/terraform/checks/resources/AzureMSSQLServerHasSecurityAlertPolicy/expected.yaml
tests/graph/terraform/checks/resources/AzureMSSQLServerHasSecurityAlertPolicy/main.tf
tests/graph/terraform/checks/resources/AzureStorageAccountsUseCustomerManagedKeyForEncryption/expected.yaml
tests/graph/terraform/checks/resources/AzureStorageAccountsUseCustomerManagedKeyForEncryption/main.tf
tests/graph/terraform/checks/resources/AzureSynapseWorkspacesHaveNoIPFirewallRulesAttached/expected.yaml
tests/graph/terraform/checks/resources/AzureSynapseWorkspacesHaveNoIPFirewallRulesAttached/main.tf
tests/graph/terraform/checks/test_yaml_policies.py

CKV_AZURE_13/18/19

---

checkov/graph/terraform/checks/aws/EncryptedEBSVolumeOnlyConnectedToEC2s.yaml
tests/graph/terraform/checks/resources/EncryptedEBSVolumeOnlyConnectedToEC2s/expected.yaml
tests/graph/terraform/checks/resources/EncryptedEBSVolumeOnlyConnectedToEC2s/main.tf
tests/graph/terraform/checks/test_yaml_policies.py

CKV2_AWS_2

---

checkov/graph/checks/checks_infra/solvers/base_solver.py
checkov/graph/terraform/checks_infra/nx_checks_parser.py
checkov/graph/terraform/checks_infra/solvers/connections_solvers/complex_connection_solver.py

Replace query_type with solver_type

---

checkov/terraform/checks/resource/azure/MariaDBGeoBackupEnabled.py
tests/terraform/checks/resource/azure/test_MariaDBGeoBackupEnabled.py

CKV_AZURE_129 - Ensure that MariaDB server enables geo-redundant backups

CKV_AZURE_129

---

checkov/graph/terraform/graph_builder/local_graph.py

remove module edge creation

---

checkov/graph/terraform/checks/aws/EIPAllocatedToVPCAttachedEC2.yaml
tests/graph/terraform/checks/resources/EIPAllocatedToVPCAttachedEC2/expected.yaml
tests/graph/terraform/checks/resources/EIPAllocatedToVPCAttachedEC2/main.tf
tests/graph/terraform/checks/test_yaml_policies.py

Ensure that all EIP addresses allocated to a VPC are attached to EC2 instances

CKV2_AWS_19

---

checkov/graph/terraform/graph_builder/local_graph.py

Don't change variable value if it is already evaluate 

Fix rendering loop

---

checkov/graph/terraform/variable_rendering/renderer.py
checkov/terraform/checks/resource/aws/AbsSecurityGroupUnrestrictedIngress.py
checkov/terraform/checks/resource/aws/DBInstanceBackupRetentionPeriod.py
checkov/terraform/checks/resource/aws/SQSPolicy.py
checkov/terraform/checks/resource/base_resource_check.py

Fix minor issues and edge cases

---

checkov/common/util/type_forcers.py
checkov/graph/terraform/graph_builder/graph_components/blocks.py
checkov/terraform/checks/resource/aws/AppLoadBalancerTLS12.py
checkov/terraform/checks/resource/aws/ECRPolicy.py
checkov/terraform/checks/resource/aws/SQSPolicy.py
checkov/terraform/checks/resource/aws/SSMSessionManagerDocumentEncryption.py
checkov/terraform/checks/resource/gcp/AbsGoogleComputeFirewallUnrestrictedIngress.py
checkov/terraform/checks/resource/gcp/GKEEnsureIntegrityMonitoring.py
checkov/terraform/checks/resource/gcp/GKELegacyInstanceMetadataDisabled.py
checkov/terraform/checks/resource/gcp/GKESecureBootforShieldedNodes.py

Centralize `is_json` and fix checks that are using `force_x`

More minor fixes

---

checkov/kubernetes/checks/WildcardRoles.py
tests/kubernetes/checks/example_WildcardRoles/role-failed-1.yaml
tests/kubernetes/checks/example_WildcardRoles/role-failed-2.yaml
tests/kubernetes/checks/example_WildcardRoles/role-failed-3.yaml
tests/kubernetes/checks/example_WildcardRoles/role-passed-1.yaml
tests/kubernetes/checks/test_WildcardRoles.py

CKV_K8S_49 Minimize wildcard use in Roles and ClusterRoles  

---

checkov/terraform/checks/resource/aws/EKSPublicAccessCIDR.py

Handle empty public CIDR blocks

---

checkov/common/graph/checks_infra/base_check.py
checkov/common/graph/checks_infra/registry.py
checkov/common/output/graph_record.py
checkov/terraform/checks_infra/checks_parser.py
checkov/terraform/runner.py

Enable suppressions on graph checks and fix name

---

checkov/kubernetes/checks/ApiServerEtcdCaFile.py
tests/kubernetes/checks/example_ApiServerEtcdCaFile/example_ApiServerEtcdCaFile-FAILED.yaml
tests/kubernetes/checks/example_ApiServerEtcdCaFile/example_ApiServerEtcdCaFile-PASSED.yaml
tests/kubernetes/checks/test_ApiServerEtcdCaFile.py

Ckv k8 s 102

---

checkov/terraform/checks/resource/aws/CloudfrontDistributionEncryption.py
checkov/terraform/checks/resource/azure/StorageAccountName.py
checkov/terraform/checks/resource/gcp/AbsGoogleIAMMemberDefaultServiceAccount.py
checkov/terraform/checks/resource/gcp/GoogleProjectAdminServiceAccount.py
checkov/terraform/variable_rendering/renderer.py

Fix empty list handling issues in 4 checks

---

checkov/terraform/checks/utils/dependency_path_handler.py
checkov/terraform/checks/utils/utils.py
checkov/terraform/graph_builder/graph_components/blocks.py
checkov/terraform/graph_builder/graph_components/module.py
checkov/terraform/graph_builder/graph_to_tf_definitions.py
checkov/terraform/graph_builder/local_graph.py
checkov/terraform/parser.py
checkov/terraform/runner.py
checkov/terraform/variable_rendering/evaluate_terraform.py
checkov/terraform/variable_rendering/renderer.py
tests/graph/terraform/graph_builder/test_graph_builder.py
tests/graph/terraform/graph_builder/test_local_graph.py
tests/graph/terraform/resources/modules-and-vars/examples/complete/main.tf
tests/graph/terraform/resources/modules/linked_modules/external_modules/terraform-aws-modules/s3-bucket/examples/notification/main.tf
tests/graph/terraform/resources/modules/s3_inner_modules/inner/main.tf
tests/graph/terraform/resources/modules/s3_inner_modules/inner/variables.tf
tests/graph/terraform/resources/modules/s3_inner_modules/main.tf
tests/graph/terraform/resources/modules/s3_inner_modules/variables.tf
tests/graph/terraform/resources/modules/stacks/prod/main.tf
tests/graph/terraform/resources/modules/stacks/prod/sub-prod/main.tf
tests/graph/terraform/resources/modules/stacks/stage/main.tf
tests/graph/terraform/resources/modules/stacks/test/main.tf
tests/graph/terraform/runner/test_runner.py
tests/graph/terraform/variable_rendering/expected_data.py
tests/graph/terraform/variable_rendering/test_render_scenario.py
tests/graph/terraform/variable_rendering/test_string_evaluation.py
tests/terraform/parser/resources/parser_scenarios/account_dirs_and_modules/expected.json
tests/terraform/parser/resources/parser_scenarios/module_matryoshka/expected.json
tests/terraform/runner/test_runner.py

1. Fix resolution of variables with modules by creating replicas matching the number of times the module is created.
2. Fix tf vars by pointing them at the variables to override the default value
3. Refactor edges rendering logic to avoid cycles
4. Break cycle in test

Module replication and resolution fixes

---

checkov/terraform/graph_builder/EncryptionCalculation.md
tests/graph/terraform/checks_infra/attribute_solvers/equals_solver/EncryptedResources.yaml
tests/graph/terraform/checks_infra/attribute_solvers/equals_solver/test_solver.py
tests/graph/terraform/resources/encryption_test/main.tf

Add encryption readme
